### ISSUE TITLE
flocker volume didn't migrate with container to new host in kubernetes env.

### ISSUE THREAD

**Issue by hgsat123** [binocarlos/flocker#1]
I have 3 node kubernetes cluster setup on ubuntu.  The details are in the attachment file
Flocker is installed with one control & 2 nodes.
[flocker_fail.txt](https://github.com/binocarlos/flocker/files/451332/flocker_fail.txt)

If you need mode info, ex flocker process logs, do let me know

**Comment by binocarlos** [comment]
[duplicate](https://github.com/ClusterHQ/flocker/issues/2894)
